[package]
name = "ethercat-derive"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
syn = "0.15"
proc-macro2 = "0.4"
